# Generated by Django 4.2.10 on 2026-03-04 09:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=30)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('brokerage_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('total_charges', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total capital impact of this order', max_digits=15)),
                ('status', models.CharField(choices=[('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='EXECUTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('brokerage_value', models.DecimalField(decimal_places=4, default=Decimal('0.0003'), help_text='Fixed amount in ₹ or percentage (e.g., 0.0003 = 0.03%)', max_digits=10)),
                ('stt_percent', models.DecimalField(decimal_places=4, default=Decimal('0.001'), help_text='Securities Transaction Tax (e.g., 0.001 = 0.1%)', max_digits=6)),
                ('gst_percent', models.DecimalField(decimal_places=4, default=Decimal('0.18'), help_text='GST on brokerage (e.g., 0.18 = 18%)', max_digits=6)),
                ('exchange_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000345'), help_text='Exchange transaction charges', max_digits=6)),
                ('slippage_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0005'), help_text='Slippage percentage (e.g., 0.0005 = 0.05%)', max_digits=6)),
                ('apply_charges', models.BooleanField(default=True, help_text='Toggle all charges on/off')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charges_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charges Configuration',
                'db_table': 'charges_config',
            },
        ),
        migrations.CreateModel(
            name='TradeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=30)),
                ('matched_quantity', models.PositiveIntegerField()),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=4, help_text='Realized profit for this matched pair (after charges)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_buy_entries', to='trading.order')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_sell_entries', to='trading.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'stock_symbol'], name='trade_ledge_user_id_266aa3_idx'), models.Index(fields=['user', 'created_at'], name='trade_ledge_user_id_229070_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=30)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'positions',
                'indexes': [models.Index(fields=['user', 'status'], name='positions_user_id_7b75ed_idx')],
                'unique_together': {('user', 'stock_symbol')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_history',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'stock_symbol', 'order_type'], name='orders_user_id_55840e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'stock_symbol', 'remaining_quantity'], name='orders_user_id_e5f1b6_idx'),
        ),
    ]
