# Generated by Django 4.2.10 on 2026-03-04 09:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=30)),
                ('matched_quantity', models.PositiveIntegerField()),
                ('buy_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sell_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=4, help_text='(sell_price - buy_price) × matched_quantity', max_digits=15)),
                ('charges_allocated', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Proportional share of total charges for this lot', max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=4, help_text='gross_profit - charges_allocated', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'trade_matching',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='net_profit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net realized profit for this SELL order (after all charges)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TradeLedger',
        ),
        migrations.AddField(
            model_name='tradematching',
            name='buy_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_matchings', to='trading.order'),
        ),
        migrations.AddField(
            model_name='tradematching',
            name='sell_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_matchings', to='trading.order'),
        ),
        migrations.AddField(
            model_name='tradematching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_matchings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradematching',
            index=models.Index(fields=['user', 'stock_symbol'], name='trade_match_user_id_1da1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='tradematching',
            index=models.Index(fields=['sell_order', 'buy_order'], name='trade_match_sell_or_7a6495_idx'),
        ),
    ]
